# Generated by Django 2.1.1 on 2018-09-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personlabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_person', models.IntegerField(db_column='id_person', max_length=30)),
                ('label', models.CharField(db_column='label', max_length=45)),
            ],
            options={
                'db_table': 'person_label',
                'managed': False,
            },
        ),
    ]
