# Generated by Django 2.1.1 on 2018-10-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_similarpeople'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(db_column='person', max_length=45)),
                ('event', models.CharField(db_column='event', max_length=45)),
            ],
            options={
                'db_table': 'person_event',
                'managed': False,
            },
        ),
    ]
